### ISSUE TITLE
[Bug] Missing lakes inside countries.

### ISSUE THREAD

**Issue by simonepri** [simonepri/geo-maps#5]
![image](https://user-images.githubusercontent.com/3505087/33100405-8a00c420-cf14-11e7-9b0c-8369ab9df173.png)

See also [here](https://www.reddit.com/r/Python/comments/7eg7we/high_quality_geojson_maps_programmatically/dq4vohm/).

**Comment by simonepri** [comment]
To solve the problem we need to subtract from:
http://data.openstreetmapdata.com/simplified-land-polygons-complete-3857.zip
these 2:
http://data.openstreetmapdata.com/lakes-polygons-reduced-3857.zip
http://data.openstreetmapdata.com/river-polygons-reduced-3857.zip

**Comment by indus** [comment]
thats not only a bug but also a feature. I'm really happy for my current project to have your lake-free data because lakes and all the small islands would make too much noise.
So maybe you can add a "inland_water_bodies" version but not replace the current?

**Comment by simonepri** [comment]
@indus May I ask you why 'countries-maritime' is not appropriate for your project if you can accept waters bodies?

**Comment by indus** [comment]
In the moment it is appropriate for my project. But I thought from the title of this issue you are going to change it so it also includes lakes inside country. After that change it wouldn't be appropriate anymore. So i just wanted to ask you to keep both versions: with and without lakes inside countries.

**Comment by simonepri** [comment]
@indus Yes, we will keep both, maybe I'll rename it.
`world-land` will be a land-only map (without lakes, rivers, oceans and seas)
`world-coast` will be the current `world-land`.
What do you think??

Just an you provide us an use case for this kind of map?
Thank You!!

**Comment by indus** [comment]
The map in my project is just the background reference to drop some informations on. For design reasons I only want to show the outline of the world and not a solid filled landmass. By doing so all the wholes (aka lakes) would distract from the information on top because only having the lines of a polygon with wholes give the viewer some challange of what is inside and what is outside - what is land and what is water. Right now I'm using mapboxs vectordata but even on the lowest zoom level it shows Great Lakes, Lake Victoria, Lake Baikal, etc. Now I want to use one of your low resolution geojsons instead.

**Comment by indus** [comment]
I've reread your comment and I wonder what land-only without oceans would look like?Am 24.11.2017 9:24 vorm. schrieb Simone Primarosa <notifications@github.com>:@indus Yes, we will keep both, maybe I'll rename it.
world-land will be a land-only map (without lakes, rivers, oceans and seas)
world-coast will be the current world-land.
What do you think??
Just an you provide us an use case for this kind of map?
Thank You!!

**Comment by simonepri** [comment]
You can see the work here https://github.com/simonepri/geo-maps/pull/12

**Comment by simonepri** [comment]
Version 0.6.0 is here with 78 new maps 🎉
